{% set python_min = "3.11" %}
{% set name = "delft_fiat" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 710a826ac7c0e5d9f71351aeec27dc0cd938f1e8977347e3d5757b88a0563331

build:
  number: 0
  noarch: python
  entry_points:
    - fiat = fiat.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0.0
  run:
    - gdal >=3.9.1
    - libgdal-netcdf
    - numpy
    - python >={{ python_min }}
    - regex

test:
  imports:
    - fiat
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://deltares.github.io/Delft-FIAT/stable/
  summary: Fast Impact Assessment Tool
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/Delft-FIAT/stable/
  dev_url: https://github.com/Deltares/Delft-FIAT

extra:
  recipe-maintainers:
    - deltares-service-account
    - dalmijn
