{% set name = "delft_fiat" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 097a78e5cad5036f42a20bd2b40648898e9f3cb9eb12e94b293d769f81f2a907

build:
  number: 0
  noarch: python
  entry_points:
    - fiat = fiat.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0.0
  run:
    - gdal >=3.9.1
    - libgdal-netcdf
    - numpy
    - python >=3.10
    - regex
    - tomli

test:
  imports:
    - fiat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Deltares/Delft-FIAT
  summary: Fast Impact Assessment Tool
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/Delft-FIAT/stable/
  dev_url: https://github.com/Deltares/Delft-FIAT

extra:
  recipe-maintainers:
    - dalmijn
