{% set name = "delft_fiat" %}
{% set version = "0.1.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d22f4655d1b56785582aa36cdf389bec672ff16c7b5242f670652415b288d8b

build:
  number: 0
  noarch: python
  entry_points:
    - fiat = fiat.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - gdal >=3.5
    - numpy
    - python >=3.7
    - regex
    - tomli

test:
  imports:
    - fiat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Deltares/Delft-FIAT
  summary: Fast Impact Assessment Tool
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/Delft-FIAT/stable/
  dev_url: https://github.com/Deltares/Delft-FIAT

extra:
  recipe-maintainers:
    - dalmijn
